"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-10 14:13:10.591870

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "owners",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("primary_admin_id", sa.String(length=64), nullable=True),
        sa.Column("billing_scope", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_owners")),
    )
    op.create_table(
        "admins",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["owners.id"], name=op.f("fk_admins_owner_id_owners")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admins")),
        sa.UniqueConstraint("email", name=op.f("uq_admins_email")),
    )
    op.create_table(
        "end_users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["owners.id"], name=op.f("fk_end_users_owner_id_owners")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_end_users")),
        sa.UniqueConstraint("email", name=op.f("uq_end_users_email")),
    )
    op.create_table(
        "assistants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("end_user_id", sa.String(length=64), nullable=False),
        sa.Column("inbound_address", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("allowed_senders", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["end_user_id"], ["end_users.id"], name=op.f("fk_assistants_end_user_id_end_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistants")),
        sa.UniqueConstraint("inbound_address", name=op.f("uq_assistants_inbound_address")),
    )
    op.create_table(
        "budgets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("assistant_id", sa.String(length=64), nullable=False),
        sa.Column("monthly_limit_cents", sa.Integer(), nullable=False),
        sa.Column("period_starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_resets_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assistant_id"], ["assistants.id"], name=op.f("fk_budgets_assistant_id_assistants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
    )
    op.create_table(
        "email_threads",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("assistant_id", sa.String(length=64), nullable=False),
        sa.Column("end_user_id", sa.String(length=64), nullable=False),
        sa.Column("root_message_id", sa.String(length=998), nullable=False),
        sa.Column("subject_normalized", sa.String(length=998), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name=op.f("fk_email_threads_assistant_id_assistants"),
        ),
        sa.ForeignKeyConstraint(
            ["end_user_id"], ["end_users.id"], name=op.f("fk_email_threads_end_user_id_end_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_threads")),
    )
    op.create_table(
        "assistant_scopes",
        sa.Column("assistant_id", sa.String(length=64), nullable=False),
        sa.Column("memory_namespace", sa.String(length=128), nullable=False),
        sa.Column("tool_allowlist", sa.JSON(), nullable=False),
        sa.Column("budget_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name=op.f("fk_assistant_scopes_assistant_id_assistants"),
        ),
        sa.ForeignKeyConstraint(
            ["budget_id"], ["budgets.id"], name=op.f("fk_assistant_scopes_budget_id_budgets")
        ),
        sa.PrimaryKeyConstraint("assistant_id", name=op.f("pk_assistant_scopes")),
    )
    op.create_table(
        "email_messages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("assistant_id", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("provider_message_id", sa.String(length=255), nullable=False),
        sa.Column("message_id_header", sa.String(length=998), nullable=False),
        sa.Column("in_reply_to_header", sa.String(length=998), nullable=True),
        sa.Column("references_headers", sa.JSON(), nullable=False),
        sa.Column("from_email", sa.String(length=320), nullable=False),
        sa.Column("to_emails", sa.JSON(), nullable=False),
        sa.Column("subject", sa.String(length=998), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name=op.f("fk_email_messages_assistant_id_assistants"),
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["email_threads.id"],
            name=op.f("fk_email_messages_thread_id_email_threads"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_messages")),
        sa.UniqueConstraint(
            "assistant_id", "provider_message_id", name=op.f("uq_email_messages_assistant_id")
        ),
    )
    op.create_table(
        "message_index",
        sa.Column("assistant_id", sa.String(length=64), nullable=False),
        sa.Column("message_id_header", sa.String(length=998), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("provider_message_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name=op.f("fk_message_index_assistant_id_assistants"),
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["email_threads.id"],
            name=op.f("fk_message_index_thread_id_email_threads"),
        ),
        sa.PrimaryKeyConstraint("assistant_id", "message_id_header", name=op.f("pk_message_index")),
        sa.UniqueConstraint(
            "assistant_id", "message_id_header", name=op.f("uq_message_index_assistant_id")
        ),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("assistant_id", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("inbound_message_id", sa.String(length=64), nullable=False),
        sa.Column("reply_message_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assistant_id"], ["assistants.id"], name=op.f("fk_agent_runs_assistant_id_assistants")
        ),
        sa.ForeignKeyConstraint(
            ["inbound_message_id"],
            ["email_messages.id"],
            name=op.f("fk_agent_runs_inbound_message_id_email_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["reply_message_id"],
            ["email_messages.id"],
            name=op.f("fk_agent_runs_reply_message_id_email_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["email_threads.id"], name=op.f("fk_agent_runs_thread_id_email_threads")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_table(
        "email_attachments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("message_id", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["email_messages.id"],
            name=op.f("fk_email_attachments_message_id_email_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_attachments")),
    )
    op.create_table(
        "run_steps",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("input_summary", sa.Text(), nullable=False),
        sa.Column("output_summary", sa.Text(), nullable=False),
        sa.Column("cost_cents", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_run_steps_run_id_agent_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_steps")),
    )
    op.create_table(
        "usage_ledger",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("assistant_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_cents", sa.Integer(), nullable=False),
        sa.Column("budget_period", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name=op.f("fk_usage_ledger_assistant_id_assistants"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_usage_ledger_run_id_agent_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_ledger")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usage_ledger")
    op.drop_table("run_steps")
    op.drop_table("email_attachments")
    op.drop_table("agent_runs")
    op.drop_table("message_index")
    op.drop_table("email_messages")
    op.drop_table("assistant_scopes")
    op.drop_table("email_threads")
    op.drop_table("budgets")
    op.drop_table("assistants")
    op.drop_table("end_users")
    op.drop_table("admins")
    op.drop_table("owners")
    # ### end Alembic commands ###
